name = "SIMDscan"
uuid = "e380c706-6fd7-45be-a86f-0677ced05258"
authors = ["Paul Schrimpf <paul.schrimpf@ubc.ca> and contributors"]
version = "0.1.0"

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
SIMD = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
